#!/bin/bash
#

# trick to pass aliases to sudo
alias sudo='sudo '

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'


    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lFh'
alias lla='ll -A'
alias la='ls -A'
alias l='ls -CF'

alias ping='ping -c 5'
alias pg='ps -Af | grep $1'

# pushd popd aliases
alias pu='pushd .'
alias po='popd'

alias g='git'

alias ..='cd ..' # Go up one directory
alias ...='cd ../..' # Go up two directories
alias ....='cd ../../..' # Go up three directories

# yaourt (manually add --noconfirm to skip prompts)
alias y='yaourt' # yaourt alias
alias yiu='comm -23 <(yaourt -Qeq|sort) <(yaourt -Qgq base base-devel|sort)' # list user installed packages
alias yu='yaourt -Syyu' # Sync and upgrade packages from pacman
alias yua='yaourt -Syyu --aur' # Sync and upgrade packages from pacman + aur
alias yr='yaourt -Rns' # Remove the specified package(s), its configuration(s) and unneeded dependencies
alias yf='yaourt -Ql' # List files for the package
alias yo='yaourt -Qdt' # List orphans


function cd()
{
     builtin cd "$*" && ls
}
