#!/bin/bash
RANGE=3
number=$RANDOM
let "number %= $RANGE"
case $number in
	0)
		cow="moose"
		;;
	1)
		cow="tux"
		;;
	2)
		cow="koala"
		;;	
esac

RANGE=2
number=$RANDOM
let "number %= $RANGE"
case $number in
	0)
		command="cowsay"
		;;
	1)
		command="cowthink"
		;;
esac
fortune | $command -f $cow


